### ISSUE TITLE
What is the specific hardware and driver? 

### ISSUE THREAD

**Issue by cgnerds** [soltesza/AR-Sandbox-for-Construction-Planning#20]
I use the Kinect for XBOX 360 (Kinect v1) and the KinectSDK-v1.8 (https://www.microsoft.com/en-us/download/details.aspx?id=40278) for test, but nothing shows, neither in the Unity editor, nor in the standalone programs. Would you kindly tell me what's the specific hardware and driver do you use? Thank you very much.
![ar](https://user-images.githubusercontent.com/3292333/41956250-86638698-7a15-11e8-9b33-77a8e92aa7ba.png)

**Comment by soltesza** [comment]
Hi there,

This project requires a Kinect V2 sensor and Kinect for Windows SDK 2.0. Thanks for your interest in this project!
